### ISSUE TITLE
No module named 'lxml.etree'

### ISSUE THREAD

**Issue by astariul** [clic-lab/newsroom#18]
When running `newsroom-scrape` cmd, I got this error :

> ModuleNotFoundError: No module named 'lxml.etree'

Full stack :

```
Traceback (most recent call last):
  File "/home/x/.venv/36/bin/newsroom-scrape", line 11, in <module>
    load_entry_point('newsroom', 'console_scripts', 'newsroom-scrape')()
  File "/home/x/.venv/36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/x/.venv/36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point    return ep.load()
  File "/home/x/.venv/36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/home/x/.venv/36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/x/.venv/36/src/newsroom/newsroom/__init__.py", line 2, in <module>
    from . import build
  File "/home/x/.venv/36/src/newsroom/newsroom/build/__init__.py", line 2, in <module>
    from .filter import Article
  File "/home/x/.venv/36/src/newsroom/newsroom/build/filter.py", line 5, in <module>
    from readability import Document
  File "/home/x/.venv/36/lib/python3.6/site-packages/readability/__init__.py", line 1, in <module>
    from .readability import Document
  File "/home/x/.venv/36/lib/python3.6/site-packages/readability/readability.py", line 8, in <module>
    from lxml.etree import tostring
ModuleNotFoundError: No module named 'lxml.etree'
```

**Comment by astariul** [comment]
After following the [installation step for lxml](https://lxml.de/installation.html), I still had the same error.

[This stackOverflow answer](https://stackoverflow.com/a/19035201/9494790) solved it.
