### ISSUE TITLE
Error when running newsroom-scrape --thin thin/dev.jsonl.gz --archive dev.archive

### ISSUE THREAD

**Issue by aburkov** [clic-lab/newsroom#6]
```
newsroom-scrape --thin thin/dev.jsonl.gz --archive dev.archive
Traceback (most recent call last):
  File "/usr/local/bin/newsroom-scrape", line 11, in <module>
    load_entry_point('newsroom', 'console_scripts', 'newsroom-scrape')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 587, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2800, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2431, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2437, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/aburkov/Downloads/src/newsroom/newsroom/__init__.py", line 2, in <module>
    from . import build
  File "/Users/aburkov/Downloads/src/newsroom/newsroom/build/__init__.py", line 1, in <module>
    from .download import Downloader
  File "/Users/aburkov/Downloads/src/newsroom/newsroom/build/download.py", line 55
    yield from executor.map(self._thread, urls)
             ^
SyntaxError: invalid syntax
```

**Comment by aburkov** [comment]
.

**Comment by FabiaMaulabux** [comment]
I am facing the same error, did you ever figure out what was wrong?
